# Generated by Django 4.0.4 on 2022-06-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
