# Generated by Django 4.0.4 on 2022-06-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default='2022-06-15 16:41:58'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
