# Generated by Django 4.0.4 on 2022-04-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0003_rename_templatetype_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table='epa_type',
        ),
    ]
