# Generated by Django 4.0.4 on 2022-04-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0004_alter_type_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
