# Generated by Django 4.0.4 on 2022-04-27 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0006_alter_template_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedd_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdd_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
