# Generated by Django 4.0.4 on 2022-04-27 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0007_appraisal_updated_by_alter_appraisal_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='appraisee',
            field=models.OneToOneField(db_column='appraisee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='appraiser',
            field=models.OneToOneField(db_column='appraiser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraiser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='template',
            field=models.ForeignKey(db_column='template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.template'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='updated_by',
            field=models.ForeignKey(db_column='updatedd_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedd_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
